/**
 * Copyright (C) 2016 - 2030 youtongluan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.yx.db.sql;

import java.util.List;

public class InsertResult {
	private int effectCount;
	private List<long[]> autoGeneratedKeys;

	public InsertResult(int effectCount, List<long[]> autoGeneratedKeys) {
		this.effectCount = effectCount;
		this.autoGeneratedKeys = autoGeneratedKeys;
	}

	public int getEffectCount() {
		return effectCount;
	}

	public List<long[]> getAutoGeneratedKeys() {
		return autoGeneratedKeys;
	}

	public long getAutoGeneratedKey() {
		if (autoGeneratedKeys == null || autoGeneratedKeys.isEmpty()) {
			return -1;
		}
		long[] row = autoGeneratedKeys.get(0);
		if (row.length == 0) {
			return -1;
		}
		return row[0];
	}
}
